import fs from 'fs';
import path from 'path';
import { glob } from 'glob';
import Groq from 'groq-sdk';
import dotenv from 'dotenv';

dotenv.config();

// 1. Setup Groq
const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY
});

// 2. Configuration
const ROOT_DIR = '.'; 
const OUTPUT_FILE = './src/data/projects.js'; // Writing directly to JS file for easy import

// 3. The Prompt Engineering (The "Soul" of the portfolio)
const SYSTEM_PROMPT = `
You are a Technical Archivist auditing a Senior Full-Stack Engineer's portfolio. 
Analyze the provided project documentation (Markdown). 
Return a STRICT JSON object (no markdown) with this exact structure suitable for a React component:
{
  "title": "A short, punchy engineering title (Max 4-5 words)",
  "tags": ["Tech1", "Tech2"], // Array of 2-3 key technologies (e.g., "Rust", "Systems", "React", "AI")
  "description": "2 sentences max. Focus on the PROBLEM solved and the TECHNICAL solution. Do not sound like marketing fluff. Sound like an engineer.",
  "colSpan": 1 // Return 2 if the project seems very complex, foundational, or "heavy" (like an OS, Compiler, or major Platform). Return 1 for standard tools/scripts.
}
`;

async function analyzeProject(filePath) {
    console.log(`🧠 Analyzing: ${filePath}...`);
    
    const content = fs.readFileSync(filePath, 'utf-8').slice(0, 8000); // Limit tokens
    
    try {
        const completion = await groq.chat.completions.create({
            messages: [
                { role: "system", content: SYSTEM_PROMPT },
                { role: "user", content: `Analyze this file:\n\n${content}` }
            ],
            model: "llama-3.3-70b-versatile", // The smart, fast model
            temperature: 0.3,
            response_format: { type: "json_object" }
        });

        const data = JSON.parse(completion.choices[0].message.content);
        
        // Add metadata matching the React app's data structure
        data.id = path.basename(filePath, '.md').toLowerCase().replace(/[^a-z0-9]/g, '-');
        // Use a default image or map based on tags if needed. For now, a placeholder.
        data.image = "/images/project-placeholder.png"; 
        data.downloadUrl = "/docs/" + path.basename(filePath); // Assuming they will be moved to /docs/
        
        return data;
    } catch (error) {
        console.error(`❌ Failed to analyze ${filePath}:`, error.message);
        return null;
    }
}

async function main() {
    console.log("🚀 Starting AI Archival Process...");

    // Find all numbered Markdown logs in the root directory
    // Matches: 01_Title.md, 12_Title.md, etc.
    const files = await glob('../[0-9][0-9]_*.md', { 
        ignore: ['node_modules/**', 'dist/**', 'README.md'] 
    });

    const projects = [];

    // Process sequentially to avoid Rate Limits
    for (const file of files) {
        const projectData = await analyzeProject(file);
        if (projectData) {
            projects.push(projectData);
            console.log(`   ✅ Indexed: ${projectData.title}`);
        }
    }

    // Generate JS content
    const fileContent = `// Auto-generated by ai-indexer.js
export const projects = ${JSON.stringify(projects, null, 2)};
`;

    // Write to React Source
    fs.writeFileSync(OUTPUT_FILE, fileContent);
    
    console.log(`\n✨ Done! Generated ${projects.length} projects in ${OUTPUT_FILE}`);
}

main();