/**
 * Escape special LaTeX characters to prevent compilation errors
 * @param {string} text - The text to escape
 * @returns {string} - Escaped text safe for LaTeX
 */
function escapeLatex(text) {
  if (!text) return '';
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/[&%$#_{}]/g, '\\$&')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}

/**
 * Generate a LaTeX resume document from provided data
 * @param {Object} data - Resume data
 * @param {string} data.name - Full name
 * @param {string} data.title - Professional title
 * @param {string} data.summary - Professional summary
 * @param {string[]} data.skills - Array of skills
 * @returns {string} - Complete LaTeX document string
 */
export function generateResumeTex(data) {
  const { name, title, summary, skills = [] } = data;

  // Escape all user input
  const safeName = escapeLatex(name);
  const safeTitle = escapeLatex(title);
  const safeSummary = escapeLatex(summary);
  const safeSkills = skills.map(skill => escapeLatex(skill));

  // Generate skills list
  const skillsLatex = safeSkills.length > 0
    ? safeSkills.map(skill => `    \\item ${skill}`).join('\n')
    : '    \\item No skills provided';

  return `\\documentclass[11pt,a4paper]{article}
\\usepackage[margin=1in]{geometry}
\\usepackage{enumitem}
\\pagestyle{empty}

\\begin{document}

% Header
\\begin{center}
  {\\Huge \\textbf{${safeName}}} \\\\[0.5em]
  {\\large ${safeTitle}}
\\end{center}

\\vspace{1em}

% Summary Section
\\section*{Professional Summary}
${safeSummary}

\\vspace{1em}

% Skills Section
\\section*{Skills}
\\begin{itemize}[noitemsep,topsep=0pt]
${skillsLatex}
\\end{itemize}

\\vspace{2em}

\\begin{center}
  \\footnotesize Generated by Second Brain OS
\\end{center}

\\end{document}`;
}
